"""initial schema: 全库一次性建表（按 2026-08-02 定稿 spec 重建）

Revision ID: 001
Revises:
Create Date: 2026-08-02

设计依据：mydocs/specs/2026-07-27_数据库表逐表审批记录.md
本次重建遵循 spec 决策#9（不兼容旧开发数据），用一份干净的 raw SQL 一次性创建全部
23 张表；旧增量迁移 002-005 已删除。

涵盖：
1. CREATE EXTENSION vector（移除 zhparser / chinese_zh / tsvector / GIN / trigger）
2. 基础设施表（7）：tenants / users / organizations / org_members / kb_shares /
   llm_providers / user_llm_keys
3. 共享根与配置（4）：knowledge_bases / kb_rag_configs / kb_wiki_configs / sources
4. 文档链（3）：documents / document_revisions / content_chunks（含 halfvec + partial HNSW）
5. Wiki（5）：wiki_folders / wiki_pages / wiki_page_links /
   wiki_page_document_refs / wiki_page_evidence_refs
6. 运行支撑（3）：processing_runs（含 ADR-0018 fencing 列）/ processing_spans / task_outbox
7. 检索日志（1）：search_logs
8. 全库不建立数据库外键（spec 决策#2，全库范围）
9. 每张表与每个字段均加中文 COMMENT（文案取自 spec 各表"说明"列）

显式不做：pg_search BM25 索引（仅删除旧 tsvector，BM25 镜像就绪后另开任务）；
org_invites / password_resets / kb_embedding_models 不建。
"""
from collections.abc import Sequence

from alembic import op

revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级：一次性创建全部 23 张表 + 索引 + CHECK + 注释。"""

    # ========== 1. 扩展 ==========
    # 仅启用 pgvector；中文分词与 BM25 由后续 pg_search 任务引入。
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ========== 2. 基础设施表 ==========

    # ----- 2.1 tenants（租户 / 自家空间） -----
    op.execute(
        """
        CREATE TABLE tenants (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id   UUID NOT NULL DEFAULT gen_random_uuid(),
            owner_id    BIGINT NOT NULL,
            name        VARCHAR(200) NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at  TIMESTAMPTZ,
            CONSTRAINT uq_tenants_public_id UNIQUE (public_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_tenants_owner_id ON tenants(owner_id)")
    op.execute("COMMENT ON TABLE tenants IS '租户（自家空间）；每个用户自注册时自动创建一条'")
    op.execute("COMMENT ON COLUMN tenants.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN tenants.public_id IS 'API、日志和导出使用的稳定公开 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN tenants.owner_id IS '拥有者 user 逻辑引用'")
    op.execute("COMMENT ON COLUMN tenants.name IS '租户名称'")
    op.execute("COMMENT ON COLUMN tenants.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN tenants.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN tenants.deleted_at IS '软删除时间'")

    # ----- 2.2 users（用户） -----
    op.execute(
        """
        CREATE TABLE users (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id           BIGINT NOT NULL,
            email               VARCHAR(255) NOT NULL,
            password_hash       VARCHAR(255) NOT NULL,
            role                VARCHAR(50) NOT NULL DEFAULT 'owner',
            is_active           BOOLEAN NOT NULL DEFAULT TRUE,
            is_email_verified   BOOLEAN NOT NULL DEFAULT FALSE,
            last_login_at       TIMESTAMPTZ,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at          TIMESTAMPTZ,
            CONSTRAINT uq_users_email UNIQUE (email)
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_users_tenant_id ON users(tenant_id) WHERE deleted_at IS NULL"
    )
    op.execute("COMMENT ON TABLE users IS '用户；MVP 单 owner，P2 多用户'")
    op.execute("COMMENT ON COLUMN users.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN users.tenant_id IS '自家 tenant 逻辑引用'")
    op.execute("COMMENT ON COLUMN users.email IS '登录邮箱，全局唯一'")
    op.execute("COMMENT ON COLUMN users.password_hash IS '密码哈希（argon2id）'")
    op.execute("COMMENT ON COLUMN users.role IS '租户内角色：owner / admin / contributor / viewer'")
    op.execute("COMMENT ON COLUMN users.is_active IS '是否启用；停用后禁止登录'")
    op.execute("COMMENT ON COLUMN users.is_email_verified IS '邮箱是否已验证'")
    op.execute("COMMENT ON COLUMN users.last_login_at IS '最近一次登录时间'")
    op.execute("COMMENT ON COLUMN users.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN users.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN users.deleted_at IS '软删除时间'")

    # ----- 2.3 organizations（共享容器） -----
    op.execute(
        """
        CREATE TABLE organizations (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id   UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id   BIGINT NOT NULL,
            owner_id    BIGINT NOT NULL,
            name        VARCHAR(200) NOT NULL,
            description TEXT NOT NULL DEFAULT '',
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at  TIMESTAMPTZ,
            CONSTRAINT uq_organizations_public_id UNIQUE (public_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_organizations_tenant_id ON organizations(tenant_id)")
    op.execute("CREATE INDEX ix_organizations_owner_id ON organizations(owner_id)")
    op.execute("COMMENT ON TABLE organizations IS '组织（共享容器）；admin 创建并邀请成员，可挂载来自不同 tenant 的 KB'")
    op.execute("COMMENT ON COLUMN organizations.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN organizations.public_id IS '稳定公开 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN organizations.tenant_id IS '创建者自家 tenant 逻辑引用'")
    op.execute("COMMENT ON COLUMN organizations.owner_id IS '组织拥有者 user 逻辑引用'")
    op.execute("COMMENT ON COLUMN organizations.name IS '组织名称'")
    op.execute("COMMENT ON COLUMN organizations.description IS '组织说明'")
    op.execute("COMMENT ON COLUMN organizations.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN organizations.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN organizations.deleted_at IS '软删除时间'")

    # ----- 2.4 org_members（组织成员关系） -----
    op.execute(
        """
        CREATE TABLE org_members (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            org_id      BIGINT NOT NULL,
            user_id     BIGINT NOT NULL,
            role        VARCHAR(50) NOT NULL DEFAULT 'viewer',
            joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_org_members_org_user UNIQUE (org_id, user_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_org_members_org_id ON org_members(org_id)")
    op.execute("CREATE INDEX ix_org_members_user_id ON org_members(user_id)")
    op.execute("COMMENT ON TABLE org_members IS '组织成员关系；人员变动只改本表，无需重写 KB 共享记录（org 级共享）'")
    op.execute("COMMENT ON COLUMN org_members.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN org_members.org_id IS '所属组织逻辑引用'")
    op.execute("COMMENT ON COLUMN org_members.user_id IS '成员 user 逻辑引用'")
    op.execute("COMMENT ON COLUMN org_members.role IS '组织内角色：admin / editor / viewer'")
    op.execute("COMMENT ON COLUMN org_members.joined_at IS '加入组织时间'")
    op.execute("COMMENT ON COLUMN org_members.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN org_members.updated_at IS '更新时间'")

    # ----- 2.5 kb_shares（KB 到组织的共享授权） -----
    op.execute(
        """
        CREATE TABLE kb_shares (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kb_id       BIGINT NOT NULL,
            org_id      BIGINT NOT NULL,
            permission  VARCHAR(50) NOT NULL DEFAULT 'read',
            shared_by   BIGINT,
            shared_at   TIMESTAMPTZ,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at  TIMESTAMPTZ,
            CONSTRAINT uq_kb_shares_kb_org UNIQUE (kb_id, org_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_kb_shares_kb_id ON kb_shares(kb_id)")
    op.execute("CREATE INDEX ix_kb_shares_org_id ON kb_shares(org_id)")
    op.execute("COMMENT ON TABLE kb_shares IS 'KB 到组织的共享授权；org 级粒度，不带 user_id'")
    op.execute("COMMENT ON COLUMN kb_shares.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN kb_shares.kb_id IS '被共享的 KB 逻辑引用'")
    op.execute("COMMENT ON COLUMN kb_shares.org_id IS '接收共享的组织逻辑引用'")
    op.execute("COMMENT ON COLUMN kb_shares.permission IS '共享权限：read / editor / admin'")
    op.execute("COMMENT ON COLUMN kb_shares.shared_by IS '发起共享的 user 逻辑引用'")
    op.execute("COMMENT ON COLUMN kb_shares.shared_at IS '发起共享时间'")
    op.execute("COMMENT ON COLUMN kb_shares.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN kb_shares.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN kb_shares.deleted_at IS '软删除时间'")

    # ----- 2.6 llm_providers（LLM 服务商） -----
    op.execute(
        """
        CREATE TABLE llm_providers (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            display_name    VARCHAR(100) NOT NULL,
            base_url        VARCHAR(500) NOT NULL DEFAULT '',
            protocol        VARCHAR(30) NOT NULL DEFAULT 'openai',
            default_models  JSONB NOT NULL DEFAULT '[]'::jsonb,
            is_active       BOOLEAN NOT NULL DEFAULT TRUE,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at      TIMESTAMPTZ
        )
        """
    )
    op.execute("COMMENT ON TABLE llm_providers IS 'LLM 服务商配置（admin 维护）；MVP 预置 1 条，P2 预置 8 个'")
    op.execute("COMMENT ON COLUMN llm_providers.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN llm_providers.display_name IS '服务商展示名'")
    op.execute("COMMENT ON COLUMN llm_providers.base_url IS 'API 基地址'")
    op.execute("COMMENT ON COLUMN llm_providers.protocol IS '协议：openai / anthropic / gemini'")
    op.execute("COMMENT ON COLUMN llm_providers.default_models IS '默认可用模型列表'")
    op.execute("COMMENT ON COLUMN llm_providers.is_active IS '是否启用'")
    op.execute("COMMENT ON COLUMN llm_providers.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN llm_providers.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN llm_providers.deleted_at IS '软删除时间'")

    # ----- 2.7 user_llm_keys（用户 BYOK 密钥） -----
    op.execute(
        """
        CREATE TABLE user_llm_keys (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id                 BIGINT NOT NULL,
            provider_id             BIGINT NOT NULL,
            encrypted_key           TEXT NOT NULL,
            selected_llm_model      VARCHAR(200),
            is_active               BOOLEAN NOT NULL DEFAULT TRUE,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at              TIMESTAMPTZ,
            CONSTRAINT uq_user_llm_keys_user_provider UNIQUE (user_id, provider_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_user_llm_keys_user_id ON user_llm_keys(user_id)")
    op.execute("CREATE INDEX ix_user_llm_keys_provider_id ON user_llm_keys(provider_id)")
    op.execute("COMMENT ON TABLE user_llm_keys IS '用户 BYOK 密钥（Fernet 加密存储）；明文不持久化'")
    op.execute("COMMENT ON COLUMN user_llm_keys.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN user_llm_keys.user_id IS '所属 user 逻辑引用'")
    op.execute("COMMENT ON COLUMN user_llm_keys.provider_id IS '绑定的服务商逻辑引用'")
    op.execute("COMMENT ON COLUMN user_llm_keys.encrypted_key IS '密钥密文'")
    op.execute("COMMENT ON COLUMN user_llm_keys.selected_llm_model IS '用户选择的 LLM 模型'")
    op.execute("COMMENT ON COLUMN user_llm_keys.is_active IS '是否启用'")
    op.execute("COMMENT ON COLUMN user_llm_keys.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN user_llm_keys.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN user_llm_keys.deleted_at IS '软删除时间'")

    # ========== 3. 共享根与配置 ==========

    # ----- 3.1 knowledge_bases（共享聚合根） -----
    op.execute(
        """
        CREATE TABLE knowledge_bases (
            id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id                   UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id                   BIGINT NOT NULL,
            name                        VARCHAR(200) NOT NULL,
            description                 TEXT NOT NULL DEFAULT '',
            chunking_strategy           VARCHAR(50) NOT NULL,
            chunk_size_tokens           INTEGER NOT NULL,
            chunk_overlap_tokens        INTEGER NOT NULL,
            chunking_options            JSONB NOT NULL DEFAULT '{}'::jsonb,
            chunking_config_version     INTEGER NOT NULL DEFAULT 1,
            created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at                  TIMESTAMPTZ,
            CONSTRAINT uq_knowledge_bases_public_id UNIQUE (public_id),
            CONSTRAINT ck_knowledge_bases_chunking_budget CHECK (
                chunk_size_tokens > 0
                AND chunk_overlap_tokens >= 0
                AND chunk_overlap_tokens < chunk_size_tokens
                AND chunking_config_version >= 1
            )
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_knowledge_bases_tenant_id ON knowledge_bases(tenant_id) WHERE deleted_at IS NULL"
    )
    op.execute("COMMENT ON TABLE knowledge_bases IS 'RAG 与 Wiki 共享的聚合根，保存身份、归属、通用描述和唯一的共享分块策略'")
    op.execute("COMMENT ON COLUMN knowledge_bases.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN knowledge_bases.public_id IS 'API、日志和导出使用的稳定公开 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN knowledge_bases.tenant_id IS '租户逻辑引用'")
    op.execute("COMMENT ON COLUMN knowledge_bases.name IS '用户可见的 KB 名称'")
    op.execute("COMMENT ON COLUMN knowledge_bases.description IS 'KB 通用说明'")
    op.execute("COMMENT ON COLUMN knowledge_bases.chunking_strategy IS '共享分块算法标识：recursive_tokens / markdown_heading / fixed_tokens / parent_child'")
    op.execute("COMMENT ON COLUMN knowledge_bases.chunk_size_tokens IS '单个共享 chunk 的目标 token 上限'")
    op.execute("COMMENT ON COLUMN knowledge_bases.chunk_overlap_tokens IS '相邻共享 chunk 重复保留的 token 数'")
    op.execute("COMMENT ON COLUMN knowledge_bases.chunking_options IS '当前分块策略的专属扩展参数，按策略 JSON Schema 校验'")
    op.execute("COMMENT ON COLUMN knowledge_bases.chunking_config_version IS '共享分块配置修订号，用于并发更新与重建追踪'")
    op.execute("COMMENT ON COLUMN knowledge_bases.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN knowledge_bases.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN knowledge_bases.deleted_at IS '软删除时间'")

    # ----- 3.2 kb_rag_configs（RAG 路径独立配置） -----
    op.execute(
        """
        CREATE TABLE kb_rag_configs (
            kb_id                   BIGINT PRIMARY KEY,
            enabled                 BOOLEAN NOT NULL DEFAULT TRUE,
            vector_enabled          BOOLEAN NOT NULL DEFAULT TRUE,
            keyword_enabled         BOOLEAN NOT NULL DEFAULT TRUE,
            embedding_model_key     VARCHAR(200),
            embedding_dim           INTEGER,
            config_version          INTEGER NOT NULL DEFAULT 1,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_kb_rag_configs_retrieval CHECK (
                NOT enabled OR vector_enabled OR keyword_enabled
            ),
            CONSTRAINT ck_kb_rag_configs_embedding CHECK (
                NOT vector_enabled
                OR (embedding_model_key IS NOT NULL AND embedding_dim > 0)
            ),
            CONSTRAINT ck_kb_rag_configs_version CHECK (config_version >= 1)
        )
        """
    )
    op.execute("COMMENT ON TABLE kb_rag_configs IS 'RAG 路径启停、召回方式与 embedding 配置；一个 KB 最多一条'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.kb_id IS 'KB 逻辑引用（主键）'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.enabled IS '暂停或启用整个 RAG 路径；暂停不删除数据'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.vector_enabled IS '是否生成向量并启用向量召回'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.keyword_enabled IS '是否建立关键词索引并启用 BM25 召回'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.embedding_model_key IS 'embedding adapter 使用的稳定模型标识'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.embedding_dim IS '模型输出维度；由模型注册信息写入，不由用户手填'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.config_version IS '配置修订号，用于并发更新和处理版本追踪'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN kb_rag_configs.updated_at IS '更新时间'")

    # ----- 3.3 kb_wiki_configs（Wiki 路径独立配置） -----
    op.execute(
        """
        CREATE TABLE kb_wiki_configs (
            kb_id                       BIGINT PRIMARY KEY,
            enabled                     BOOLEAN NOT NULL DEFAULT TRUE,
            generation_mode             VARCHAR(20) NOT NULL DEFAULT 'manual',
            generation_model_key        VARCHAR(200),
            generation_options          JSONB NOT NULL DEFAULT '{}'::jsonb,
            config_version              INTEGER NOT NULL DEFAULT 1,
            created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_kb_wiki_configs_mode CHECK (generation_mode IN ('manual', 'on_ingest')),
            CONSTRAINT ck_kb_wiki_configs_version CHECK (config_version >= 1)
        )
        """
    )
    op.execute("COMMENT ON TABLE kb_wiki_configs IS 'Wiki 路径启停和页面生成配置；一个 KB 最多一条'")
    op.execute("COMMENT ON COLUMN kb_wiki_configs.kb_id IS 'KB 逻辑引用（主键）'")
    op.execute("COMMENT ON COLUMN kb_wiki_configs.enabled IS '暂停或启用整个 Wiki 路径；暂停不删除页面'")
    op.execute("COMMENT ON COLUMN kb_wiki_configs.generation_mode IS '生成模式：manual 或 on_ingest'")
    op.execute("COMMENT ON COLUMN kb_wiki_configs.generation_model_key IS '自动生成 Wiki 页面使用的 LLM；NULL 表示使用系统默认模型'")
    op.execute("COMMENT ON COLUMN kb_wiki_configs.generation_options IS '自动生成页面类型、输出语言和 prompt profile 等策略参数'")
    op.execute("COMMENT ON COLUMN kb_wiki_configs.config_version IS 'Wiki 配置修订号'")
    op.execute("COMMENT ON COLUMN kb_wiki_configs.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN kb_wiki_configs.updated_at IS '更新时间'")

    # ----- 3.4 sources（文档来源） -----
    op.execute(
        """
        CREATE TABLE sources (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id       UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id       BIGINT NOT NULL,
            kb_id           BIGINT NOT NULL,
            source_type     VARCHAR(50) NOT NULL,
            name            VARCHAR(255) NOT NULL,
            enabled         BOOLEAN NOT NULL DEFAULT TRUE,
            config          JSONB NOT NULL DEFAULT '{}'::jsonb,
            sync_cursor     JSONB NOT NULL DEFAULT '{}'::jsonb,
            config_version  INTEGER NOT NULL DEFAULT 1,
            last_synced_at  TIMESTAMPTZ,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at      TIMESTAMPTZ,
            CONSTRAINT uq_sources_public_id UNIQUE (public_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_sources_tenant_id ON sources(tenant_id) WHERE deleted_at IS NULL")
    op.execute("CREATE INDEX ix_sources_kb_id ON sources(kb_id) WHERE deleted_at IS NULL")
    op.execute("CREATE INDEX ix_sources_source_type ON sources(source_type) WHERE deleted_at IS NULL")
    # 未删除 manual Source 每 (tenant, kb) 唯一，避免并发上传产生重复 manual Source。
    op.execute(
        """
        CREATE UNIQUE INDEX uq_sources_manual_active_per_kb
            ON sources (tenant_id, kb_id, source_type)
            WHERE source_type = 'manual' AND deleted_at IS NULL
        """
    )
    op.execute("COMMENT ON TABLE sources IS '文档进入 KB 的来源或连接器；一个 Source 可产生多篇 Documents'")
    op.execute("COMMENT ON COLUMN sources.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN sources.public_id IS 'API、日志和导出使用的稳定公开 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN sources.tenant_id IS '租户隔离过滤'")
    op.execute("COMMENT ON COLUMN sources.kb_id IS 'KB 逻辑引用'")
    op.execute("COMMENT ON COLUMN sources.source_type IS '已注册的 Source Adapter 类型；MVP 为 manual'")
    op.execute("COMMENT ON COLUMN sources.name IS '用户可修改的显示名称，不作为同步身份'")
    op.execute("COMMENT ON COLUMN sources.enabled IS '是否继续接收上传或执行同步；暂停不删除已有内容'")
    op.execute("COMMENT ON COLUMN sources.config IS 'Adapter 非敏感配置；按 source_type 对应 JSON Schema 校验'")
    op.execute("COMMENT ON COLUMN sources.sync_cursor IS 'Adapter 增量同步游标（结构化 JSON）；只有同步成功后才更新'")
    op.execute("COMMENT ON COLUMN sources.config_version IS 'Source 配置修订号'")
    op.execute("COMMENT ON COLUMN sources.last_synced_at IS '最近一次成功完成同步的时间'")
    op.execute("COMMENT ON COLUMN sources.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN sources.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN sources.deleted_at IS '软删除时间'")

    # ========== 4. 文档链 ==========

    # ----- 4.1 documents（逻辑文档稳定身份） -----
    op.execute(
        """
        CREATE TABLE documents (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id               UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id               BIGINT NOT NULL,
            kb_id                   BIGINT NOT NULL,
            source_id               BIGINT NOT NULL,
            source_document_key     VARCHAR(512) NOT NULL,
            title                   VARCHAR(500) NOT NULL,
            active_revision_id      BIGINT,
            version                 INTEGER NOT NULL DEFAULT 1,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at              TIMESTAMPTZ,
            CONSTRAINT uq_documents_public_id UNIQUE (public_id),
            CONSTRAINT ck_documents_version CHECK (version >= 1)
        )
        """
    )
    op.execute("CREATE INDEX ix_documents_tenant_id ON documents(tenant_id) WHERE deleted_at IS NULL")
    op.execute("CREATE INDEX ix_documents_kb_id ON documents(kb_id) WHERE deleted_at IS NULL")
    op.execute("CREATE INDEX ix_documents_source_id ON documents(source_id) WHERE deleted_at IS NULL")
    op.execute("CREATE INDEX ix_documents_active_revision_id ON documents(active_revision_id)")
    # 未删除记录中 (source_id, source_document_key) 唯一。
    op.execute(
        """
        CREATE UNIQUE INDEX uq_documents_source_key_active
            ON documents(source_id, source_document_key) WHERE deleted_at IS NULL
        """
    )
    op.execute("COMMENT ON TABLE documents IS '来源文档在 KB 中的稳定身份；同一来源文档更新时不删除重建'")
    op.execute("COMMENT ON COLUMN documents.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN documents.public_id IS 'API 对外文档 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN documents.tenant_id IS '租户逻辑引用'")
    op.execute("COMMENT ON COLUMN documents.kb_id IS 'KB 逻辑引用'")
    op.execute("COMMENT ON COLUMN documents.source_id IS 'Source 逻辑引用'")
    op.execute("COMMENT ON COLUMN documents.source_document_key IS '来源系统中的稳定文档标识；手动上传时生成，不使用文件名充当身份'")
    op.execute("COMMENT ON COLUMN documents.title IS '当前展示标题'")
    op.execute("COMMENT ON COLUMN documents.active_revision_id IS '当前已通过激活门槛、正式供 RAG/Wiki 使用的版本；首次激活成功前为空'")
    op.execute("COMMENT ON COLUMN documents.version IS '修改文档元数据时的乐观锁'")
    op.execute("COMMENT ON COLUMN documents.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN documents.updated_at IS '更新时间'")
    op.execute("COMMENT ON COLUMN documents.deleted_at IS '软删除时间'")

    # ----- 4.2 document_revisions（不可变文档版本） -----
    op.execute(
        """
        CREATE TABLE document_revisions (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_id         BIGINT NOT NULL,
            revision_no         INTEGER NOT NULL,
            source_version      VARCHAR(255),
            source_updated_at   TIMESTAMPTZ,
            original_filename   VARCHAR(500) NOT NULL,
            media_type          VARCHAR(255) NOT NULL,
            size_bytes          BIGINT NOT NULL,
            content_sha256      CHAR(64) NOT NULL,
            storage_key         VARCHAR(1000) NOT NULL,
            parser_engine       VARCHAR(50) NOT NULL DEFAULT 'builtin',
            status              VARCHAR(20) NOT NULL DEFAULT 'pending',
            parse_metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_by_user_id  BIGINT,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at          TIMESTAMPTZ,
            CONSTRAINT uq_document_revisions_number UNIQUE (document_id, revision_no),
            CONSTRAINT uq_document_revisions_storage_key UNIQUE (storage_key),
            CONSTRAINT ck_document_revisions_revision_no CHECK (revision_no >= 1),
            CONSTRAINT ck_document_revisions_size CHECK (size_bytes >= 0),
            CONSTRAINT ck_document_revisions_status CHECK (status IN ('pending', 'processing', 'ready', 'failed')),
            CONSTRAINT ck_document_revisions_sha256 CHECK (content_sha256 ~ '^[0-9a-f]{64}$')
        )
        """
    )
    op.execute("CREATE INDEX ix_document_revisions_document ON document_revisions(document_id)")
    op.execute("CREATE INDEX ix_document_revisions_content_sha256 ON document_revisions(content_sha256)")
    # 有 source_version 时，未删除记录中 (document_id, source_version) 唯一。
    op.execute(
        """
        CREATE UNIQUE INDEX uq_document_revisions_source_version_active
            ON document_revisions(document_id, source_version)
            WHERE source_version IS NOT NULL AND deleted_at IS NULL
        """
    )
    op.execute("COMMENT ON TABLE document_revisions IS '一次上传或同步取得的内容快照；原文件事实不可修改，status 只表达能否成为生效版本'")
    op.execute("COMMENT ON COLUMN document_revisions.id IS '内部版本 ID'")
    op.execute("COMMENT ON COLUMN document_revisions.document_id IS 'Document 逻辑引用'")
    op.execute("COMMENT ON COLUMN document_revisions.revision_no IS '文档内单调递增版本号'")
    op.execute("COMMENT ON COLUMN document_revisions.source_version IS '来源系统提供的 revision ID、ETag 等幂等标识'")
    op.execute("COMMENT ON COLUMN document_revisions.source_updated_at IS '来源系统声明的修改时间'")
    op.execute("COMMENT ON COLUMN document_revisions.original_filename IS '本版本收到的原始文件名'")
    op.execute("COMMENT ON COLUMN document_revisions.media_type IS 'MIME 类型'")
    op.execute("COMMENT ON COLUMN document_revisions.size_bytes IS '原文件字节数'")
    op.execute("COMMENT ON COLUMN document_revisions.content_sha256 IS '原文件内容指纹'")
    op.execute("COMMENT ON COLUMN document_revisions.storage_key IS '对象存储中的不可变 key'")
    op.execute("COMMENT ON COLUMN document_revisions.parser_engine IS '本版本选择的解析引擎'")
    op.execute("COMMENT ON COLUMN document_revisions.status IS 'pending / processing / ready / failed'")
    op.execute("COMMENT ON COLUMN document_revisions.parse_metadata IS 'parser metadata、warnings 与持久化图片清单，禁止 base64'")
    op.execute("COMMENT ON COLUMN document_revisions.created_by_user_id IS '手动上传者；自动同步时为空'")
    op.execute("COMMENT ON COLUMN document_revisions.created_at IS '版本创建时间'")
    op.execute("COMMENT ON COLUMN document_revisions.updated_at IS '状态或解析元数据更新时间'")
    op.execute("COMMENT ON COLUMN document_revisions.deleted_at IS '软删除时间'")

    # ----- 4.3 content_chunks（共享内容块 + halfvec 向量） -----
    # halfvec 列不带 N，查询时 cast 为 halfvec(N) 才能命中 partial HNSW（参 ADR-0001）。
    # 不保留 search_vector / chunk_type / wiki_page_id / deleted_at（spec 决策）。
    op.execute(
        """
        CREATE TABLE content_chunks (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id           UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id           BIGINT NOT NULL,
            kb_id               BIGINT NOT NULL,
            source_id           BIGINT NOT NULL,
            document_id         BIGINT NOT NULL,
            revision_id         BIGINT NOT NULL,
            processing_run_id   BIGINT NOT NULL,
            embedding_run_id    BIGINT,
            chunk_index         INTEGER NOT NULL,
            text                TEXT NOT NULL,
            token_count         INTEGER NOT NULL,
            text_sha256         CHAR(64) NOT NULL,
            source_locator      JSONB NOT NULL DEFAULT '{}'::jsonb,
            embedding           halfvec,
            embedding_dim       INTEGER,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_content_chunks_public_id UNIQUE (public_id),
            CONSTRAINT uq_content_chunks_revision_index UNIQUE (revision_id, chunk_index),
            CONSTRAINT ck_content_chunks_nonempty_text CHECK (length(btrim(text)) > 0),
            CONSTRAINT ck_content_chunks_chunk_index CHECK (chunk_index >= 0),
            CONSTRAINT ck_content_chunks_token_count CHECK (token_count >= 0),
            CONSTRAINT ck_content_chunks_embedding_dim CHECK (embedding_dim IS NULL OR embedding_dim > 0),
            CONSTRAINT ck_content_chunks_embedding_shape CHECK (
                (embedding IS NULL AND embedding_dim IS NULL AND embedding_run_id IS NULL)
                OR
                (embedding IS NOT NULL AND embedding_dim > 0 AND embedding_run_id IS NOT NULL)
            )
        )
        """
    )
    # partial HNSW 索引（按维度分）；bge-m3 默认 1024 维。
    # 固定 m=16、ef_construction=64（spec 决策#8）；不带 deleted_at 条件（本表无 deleted_at）。
    op.execute(
        """
        CREATE INDEX content_chunks_embedding_1024_hnsw
            ON content_chunks
            USING hnsw ((embedding::halfvec(1024)) halfvec_cosine_ops)
            WITH (m = 16, ef_construction = 64)
            WHERE embedding_dim = 1024
        """
    )
    op.execute("CREATE INDEX ix_content_chunks_tenant_kb ON content_chunks(tenant_id, kb_id)")
    op.execute("CREATE INDEX ix_content_chunks_source ON content_chunks(source_id)")
    op.execute("CREATE INDEX ix_content_chunks_document_index ON content_chunks(document_id, chunk_index)")
    op.execute("CREATE INDEX ix_content_chunks_processing_run ON content_chunks(processing_run_id)")
    op.execute(
        "CREATE INDEX ix_content_chunks_embedding_run ON content_chunks(embedding_run_id) WHERE embedding_run_id IS NOT NULL"
    )
    op.execute("COMMENT ON TABLE content_chunks IS 'Active Revision 的共享内容块；同时作为 RAG 召回单元与 Wiki Map 输入'")
    op.execute("COMMENT ON COLUMN content_chunks.id IS '内部 ID，也是后续 pg_search BM25 的 key_field'")
    op.execute("COMMENT ON COLUMN content_chunks.public_id IS 'API 对外 chunk ID，全局唯一'")
    op.execute("COMMENT ON COLUMN content_chunks.tenant_id IS '租户过滤'")
    op.execute("COMMENT ON COLUMN content_chunks.kb_id IS 'KB 过滤'")
    op.execute("COMMENT ON COLUMN content_chunks.source_id IS '来源过滤'")
    op.execute("COMMENT ON COLUMN content_chunks.document_id IS '逻辑文档引用'")
    op.execute("COMMENT ON COLUMN content_chunks.revision_id IS '生效文档版本引用'")
    op.execute("COMMENT ON COLUMN content_chunks.processing_run_id IS '解析并生成本共享 chunk 的 document_process Run'")
    op.execute("COMMENT ON COLUMN content_chunks.embedding_run_id IS '最近一次写入当前 embedding 的 rag_index Run；未向量化时为空'")
    op.execute("COMMENT ON COLUMN content_chunks.chunk_index IS '文档内从 0 开始的顺序'")
    op.execute("COMMENT ON COLUMN content_chunks.text IS '共享原文块；同时作为 BM25 原文、embedding 输入和 Wiki Map 输入'")
    op.execute("COMMENT ON COLUMN content_chunks.token_count IS '上下文 token 预算'")
    op.execute("COMMENT ON COLUMN content_chunks.text_sha256 IS '文本指纹，用于 embedding 缓存与重复检测'")
    op.execute("COMMENT ON COLUMN content_chunks.source_locator IS 'PDF 页码、Excel sheet/行号、Markdown 标题路径等原文位置'")
    op.execute("COMMENT ON COLUMN content_chunks.embedding IS 'RAG 语义向量；Wiki-only、仅关键词或尚未完成向量化时为空'")
    op.execute("COMMENT ON COLUMN content_chunks.embedding_dim IS '与 embedding 同时为空或同时存在'")
    op.execute("COMMENT ON COLUMN content_chunks.created_at IS '生成时间'")
    op.execute("COMMENT ON COLUMN content_chunks.updated_at IS 'embedding 写入或重建的最近更新时间'")

    # ========== 5. Wiki 表 ==========

    # ----- 5.1 wiki_folders（目录树） -----
    op.execute(
        """
        CREATE TABLE wiki_folders (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id           UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id           BIGINT NOT NULL,
            kb_id               BIGINT NOT NULL,
            parent_id           BIGINT,
            name                VARCHAR(255) NOT NULL,
            slug                VARCHAR(255) NOT NULL,
            sort_order          INTEGER NOT NULL DEFAULT 0,
            version             INTEGER NOT NULL DEFAULT 1,
            created_by_user_id  BIGINT,
            updated_by_user_id  BIGINT,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at          TIMESTAMPTZ,
            CONSTRAINT uq_wiki_folders_public_id UNIQUE (public_id),
            CONSTRAINT ck_wiki_folders_name CHECK (length(btrim(name)) > 0),
            CONSTRAINT ck_wiki_folders_slug CHECK (length(btrim(slug)) > 0),
            CONSTRAINT ck_wiki_folders_version CHECK (version >= 1)
        )
        """
    )
    # 未删除根级文件夹 (kb_id, slug) 唯一。
    op.execute(
        """
        CREATE UNIQUE INDEX uq_wiki_folders_root_slug_active
            ON wiki_folders(kb_id, slug)
            WHERE parent_id IS NULL AND deleted_at IS NULL
        """
    )
    # 未删除普通文件夹 (kb_id, parent_id, slug) 唯一。
    op.execute(
        """
        CREATE UNIQUE INDEX uq_wiki_folders_child_slug_active
            ON wiki_folders(kb_id, parent_id, slug)
            WHERE parent_id IS NOT NULL AND deleted_at IS NULL
        """
    )
    op.execute("CREATE INDEX ix_wiki_folders_tenant_kb ON wiki_folders(tenant_id, kb_id)")
    op.execute("CREATE INDEX ix_wiki_folders_tree ON wiki_folders(kb_id, parent_id, sort_order, id)")
    op.execute("CREATE INDEX ix_wiki_folders_parent ON wiki_folders(parent_id)")
    op.execute("COMMENT ON TABLE wiki_folders IS 'Wiki 左侧目录树；只保存单层父子关系，不缓存完整路径或深度'")
    op.execute("COMMENT ON COLUMN wiki_folders.id IS '内部文件夹 ID'")
    op.execute("COMMENT ON COLUMN wiki_folders.public_id IS 'API 使用的稳定公开 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN wiki_folders.tenant_id IS '租户隔离过滤'")
    op.execute("COMMENT ON COLUMN wiki_folders.kb_id IS '文件夹所属 KB'")
    op.execute("COMMENT ON COLUMN wiki_folders.parent_id IS '父文件夹逻辑引用；NULL 表示 Wiki 根目录下的一级文件夹'")
    op.execute("COMMENT ON COLUMN wiki_folders.name IS '用户可见名称，允许修改'")
    op.execute("COMMENT ON COLUMN wiki_folders.slug IS '稳定且文件系统安全的 Markdown 导出路径段，创建后不可修改'")
    op.execute("COMMENT ON COLUMN wiki_folders.sort_order IS '同一父目录内的人工排序权重'")
    op.execute("COMMENT ON COLUMN wiki_folders.version IS '移动、改名和排序时的乐观锁'")
    op.execute("COMMENT ON COLUMN wiki_folders.created_by_user_id IS '创建者；系统创建时为空'")
    op.execute("COMMENT ON COLUMN wiki_folders.updated_by_user_id IS '最近修改者；系统修改时为空'")
    op.execute("COMMENT ON COLUMN wiki_folders.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN wiki_folders.updated_at IS '最近修改时间'")
    op.execute("COMMENT ON COLUMN wiki_folders.deleted_at IS '软删除时间'")

    # ----- 5.2 wiki_pages（页面正文） -----
    op.execute(
        """
        CREATE TABLE wiki_pages (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id               UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id               BIGINT NOT NULL,
            kb_id                   BIGINT NOT NULL,
            page_type               VARCHAR(20) NOT NULL,
            slug                    VARCHAR(255) NOT NULL,
            title                   VARCHAR(500) NOT NULL,
            aliases                 TEXT[] NOT NULL DEFAULT '{}',
            excerpt                 TEXT,
            content                 TEXT NOT NULL DEFAULT '',
            folder_id               BIGINT,
            sort_order              INTEGER NOT NULL DEFAULT 0,
            version                 INTEGER NOT NULL DEFAULT 1,
            created_by_user_id      BIGINT,
            updated_by_user_id      BIGINT,
            generation_run_id       BIGINT,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at              TIMESTAMPTZ,
            CONSTRAINT uq_wiki_pages_public_id UNIQUE (public_id),
            CONSTRAINT ck_wiki_pages_page_type CHECK (page_type IN ('summary', 'entity', 'concept', 'index', 'log', 'synthesis', 'comparison')),
            CONSTRAINT ck_wiki_pages_slug CHECK (length(btrim(slug)) > 0),
            CONSTRAINT ck_wiki_pages_title CHECK (length(btrim(title)) > 0),
            CONSTRAINT ck_wiki_pages_version CHECK (version >= 1)
        )
        """
    )
    # 未删除页面 (kb_id, slug) 唯一。
    op.execute(
        "CREATE UNIQUE INDEX uq_wiki_pages_kb_slug_active ON wiki_pages(kb_id, slug) WHERE deleted_at IS NULL"
    )
    op.execute("CREATE INDEX ix_wiki_pages_tenant_kb ON wiki_pages(tenant_id, kb_id)")
    op.execute("CREATE INDEX ix_wiki_pages_kb_type ON wiki_pages(kb_id, page_type)")
    op.execute("CREATE INDEX ix_wiki_pages_folder ON wiki_pages(kb_id, folder_id, sort_order, id)")
    op.execute("CREATE INDEX ix_wiki_pages_generation_run ON wiki_pages(generation_run_id)")
    op.execute("COMMENT ON TABLE wiki_pages IS 'Wiki 页面的稳定身份、类型、展示内容、目录归属和编辑并发状态'")
    op.execute("COMMENT ON COLUMN wiki_pages.id IS '内部关联 ID'")
    op.execute("COMMENT ON COLUMN wiki_pages.public_id IS 'API 对外稳定页面 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN wiki_pages.tenant_id IS '租户逻辑引用与隔离过滤'")
    op.execute("COMMENT ON COLUMN wiki_pages.kb_id IS 'KB 逻辑引用'")
    op.execute("COMMENT ON COLUMN wiki_pages.page_type IS 'summary / entity / concept / index / log / synthesis / comparison'")
    op.execute("COMMENT ON COLUMN wiki_pages.slug IS 'KB 内稳定页面标识，用于 URL 与 wikilink，创建后不可修改'")
    op.execute("COMMENT ON COLUMN wiki_pages.title IS '用户看到的页面标题'")
    op.execute("COMMENT ON COLUMN wiki_pages.aliases IS '简称、旧称和中英文名称，只辅助搜索'")
    op.execute("COMMENT ON COLUMN wiki_pages.excerpt IS '页面简短预览，用于目录列表、搜索结果和 Agent 选页'")
    op.execute("COMMENT ON COLUMN wiki_pages.content IS '完整 Markdown 正文'")
    op.execute("COMMENT ON COLUMN wiki_pages.folder_id IS '页面真实目录归属；NULL 表示 Wiki 根目录或无普通目录的系统页'")
    op.execute("COMMENT ON COLUMN wiki_pages.sort_order IS '同一目录内的人工排序权重'")
    op.execute("COMMENT ON COLUMN wiki_pages.version IS '编辑乐观锁；成功修改后递增'")
    op.execute("COMMENT ON COLUMN wiki_pages.created_by_user_id IS '创建者；系统或 Agent 创建时为空'")
    op.execute("COMMENT ON COLUMN wiki_pages.updated_by_user_id IS '最近一次人工修改者；系统更新时为空'")
    op.execute("COMMENT ON COLUMN wiki_pages.generation_run_id IS '最近一次写入该页面的 Wiki 生成运行'")
    op.execute("COMMENT ON COLUMN wiki_pages.created_at IS '首次创建时间'")
    op.execute("COMMENT ON COLUMN wiki_pages.updated_at IS '最近更新时间'")
    op.execute("COMMENT ON COLUMN wiki_pages.deleted_at IS '软删除时间'")

    # ----- 5.3 wiki_page_links（页面间有向链接） -----
    op.execute(
        """
        CREATE TABLE wiki_page_links (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id       BIGINT NOT NULL,
            kb_id           BIGINT NOT NULL,
            from_page_id    BIGINT NOT NULL,
            to_page_id      BIGINT,
            target_slug     VARCHAR(255) NOT NULL,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_wiki_page_links_from_target UNIQUE (from_page_id, target_slug),
            CONSTRAINT ck_wiki_page_links_target_slug CHECK (length(btrim(target_slug)) > 0)
        )
        """
    )
    op.execute("CREATE INDEX ix_wiki_page_links_to_from ON wiki_page_links(to_page_id, from_page_id)")
    op.execute("CREATE INDEX ix_wiki_page_links_kb_slug ON wiki_page_links(kb_id, target_slug)")
    op.execute("CREATE INDEX ix_wiki_page_links_tenant_kb ON wiki_page_links(tenant_id, kb_id)")
    op.execute("COMMENT ON TABLE wiki_page_links IS '从 wiki_pages.content 中 [[slug|显示文字]] 同步解析出的页面间有向关系'")
    op.execute("COMMENT ON COLUMN wiki_page_links.id IS '内部链接记录 ID'")
    op.execute("COMMENT ON COLUMN wiki_page_links.tenant_id IS '租户隔离过滤'")
    op.execute("COMMENT ON COLUMN wiki_page_links.kb_id IS 'KB 逻辑引用与链接解析范围'")
    op.execute("COMMENT ON COLUMN wiki_page_links.from_page_id IS '发出 wikilink 的来源页面'")
    op.execute("COMMENT ON COLUMN wiki_page_links.to_page_id IS '已解析目标页面；目标尚不存在或被软删除时为空'")
    op.execute("COMMENT ON COLUMN wiki_page_links.target_slug IS 'Markdown 中声明的不可变目标 slug；用于悬空链接和后续自动解析'")
    op.execute("COMMENT ON COLUMN wiki_page_links.created_at IS '首次提取该链接的时间'")
    op.execute("COMMENT ON COLUMN wiki_page_links.updated_at IS '链接解析状态更新时间'")

    # ----- 5.4 wiki_page_document_refs（页面到文档版本的来源关系） -----
    op.execute(
        """
        CREATE TABLE wiki_page_document_refs (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id       BIGINT NOT NULL,
            kb_id           BIGINT NOT NULL,
            wiki_page_id    BIGINT NOT NULL,
            document_id     BIGINT NOT NULL,
            revision_id     BIGINT NOT NULL,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_wiki_page_document_refs_page_rev UNIQUE (wiki_page_id, revision_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_wiki_page_document_refs_tenant_kb ON wiki_page_document_refs(tenant_id, kb_id)")
    op.execute("CREATE INDEX ix_wiki_page_document_refs_page ON wiki_page_document_refs(wiki_page_id, id)")
    op.execute("CREATE INDEX ix_wiki_page_document_refs_doc ON wiki_page_document_refs(document_id, wiki_page_id)")
    op.execute("CREATE INDEX ix_wiki_page_document_refs_rev ON wiki_page_document_refs(revision_id, wiki_page_id)")
    op.execute("COMMENT ON TABLE wiki_page_document_refs IS 'Wiki 页面使用过的文档及具体不可变 Revision，是页面级来源清单'")
    op.execute("COMMENT ON COLUMN wiki_page_document_refs.id IS '内部来源关系 ID'")
    op.execute("COMMENT ON COLUMN wiki_page_document_refs.tenant_id IS '租户隔离过滤'")
    op.execute("COMMENT ON COLUMN wiki_page_document_refs.kb_id IS 'KB 隔离过滤'")
    op.execute("COMMENT ON COLUMN wiki_page_document_refs.wiki_page_id IS 'Wiki 页面逻辑引用'")
    op.execute("COMMENT ON COLUMN wiki_page_document_refs.document_id IS '稳定 Document 逻辑引用，用于文档导航和按文档反查页面'")
    op.execute("COMMENT ON COLUMN wiki_page_document_refs.revision_id IS '页面实际使用的不可变 Document Revision；文档产生新版时不自动漂移'")
    op.execute("COMMENT ON COLUMN wiki_page_document_refs.created_at IS '当前来源关系建立时间'")

    # ----- 5.5 wiki_page_evidence_refs（原文证据级血缘） -----
    op.execute(
        """
        CREATE TABLE wiki_page_evidence_refs (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id           BIGINT NOT NULL,
            kb_id               BIGINT NOT NULL,
            wiki_page_id        BIGINT NOT NULL,
            document_id         BIGINT NOT NULL,
            revision_id         BIGINT NOT NULL,
            evidence_quote      TEXT NOT NULL,
            evidence_sha256     CHAR(64) NOT NULL,
            source_locator      JSONB NOT NULL,
            content_chunk_id    BIGINT,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_wiki_page_evidence_refs_page_sha UNIQUE (wiki_page_id, evidence_sha256),
            CONSTRAINT ck_wiki_page_evidence_refs_quote CHECK (length(btrim(evidence_quote)) > 0),
            CONSTRAINT ck_wiki_page_evidence_refs_sha256 CHECK (evidence_sha256 ~ '^[0-9a-f]{64}$')
        )
        """
    )
    op.execute("CREATE INDEX ix_wiki_page_evidence_refs_tenant_kb ON wiki_page_evidence_refs(tenant_id, kb_id)")
    op.execute("CREATE INDEX ix_wiki_page_evidence_refs_page ON wiki_page_evidence_refs(wiki_page_id, id)")
    op.execute("CREATE INDEX ix_wiki_page_evidence_refs_doc_rev ON wiki_page_evidence_refs(document_id, revision_id)")
    op.execute("CREATE INDEX ix_wiki_page_evidence_refs_rev_page ON wiki_page_evidence_refs(revision_id, wiki_page_id)")
    op.execute(
        "CREATE INDEX ix_wiki_page_evidence_refs_chunk ON wiki_page_evidence_refs(content_chunk_id) WHERE content_chunk_id IS NOT NULL"
    )
    op.execute("COMMENT ON TABLE wiki_page_evidence_refs IS 'Wiki 页面实际依据的精确原文证据；Revision、引文和位置是 chunk 删除后仍有效的长期证据'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.id IS '内部证据记录 ID'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.tenant_id IS '租户隔离过滤'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.kb_id IS 'KB 隔离过滤'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.wiki_page_id IS '使用这条证据的 Wiki 页面'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.document_id IS '证据所属的稳定 Document'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.revision_id IS '证据所属的具体不可变 Revision'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.evidence_quote IS '应用从共享 chunk 中核验复制的准确原文；不得信任 AI 自由改写后写入'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.evidence_sha256 IS '对 Revision、规范化位置和规范化引用计算的指纹，用于消除重复证据'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.source_locator IS 'PDF 页码、标题路径、Excel sheet/行号、段落范围等原文位置'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.content_chunk_id IS '生成证据时使用的共享 content_chunks 逻辑引用；该 chunk 删除后清空'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.created_at IS '证据创建时间'")
    op.execute("COMMENT ON COLUMN wiki_page_evidence_refs.updated_at IS '清空 content_chunk_id 等关联状态的更新时间'")

    # ========== 6. 运行支撑表 ==========

    # ----- 6.1 processing_runs（含 ADR-0018 fencing 列） -----
    op.execute(
        """
        CREATE TABLE processing_runs (
            id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id                   UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id                   BIGINT NOT NULL,
            kb_id                       BIGINT NOT NULL,
            run_type                    VARCHAR(50) NOT NULL,
            scope_type                  VARCHAR(30) NOT NULL,
            scope_id                    BIGINT NOT NULL,
            parent_run_id               BIGINT,
            retry_of_run_id             BIGINT,
            attempt_no                  INTEGER NOT NULL DEFAULT 1,
            trigger_type                VARCHAR(20) NOT NULL,
            status                      VARCHAR(20) NOT NULL DEFAULT 'pending',
            idempotency_key             VARCHAR(255),
            effective_config_version    INTEGER,
            options_snapshot            JSONB NOT NULL DEFAULT '{}'::jsonb,
            requested_by_user_id        BIGINT,
            error_code                  VARCHAR(50),
            error_message               VARCHAR(1000),
            execution_token             UUID,
            execution_epoch             INTEGER NOT NULL DEFAULT 0,
            lease_expires_at            TIMESTAMPTZ,
            worker_id                   VARCHAR(255),
            started_at                  TIMESTAMPTZ,
            heartbeat_at                TIMESTAMPTZ,
            finished_at                 TIMESTAMPTZ,
            created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_processing_runs_public_id UNIQUE (public_id),
            CONSTRAINT ck_processing_runs_attempt CHECK (attempt_no >= 1),
            CONSTRAINT ck_processing_runs_config_version CHECK (
                effective_config_version IS NULL OR effective_config_version >= 1
            ),
            CONSTRAINT ck_processing_runs_status CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
            CONSTRAINT ck_processing_runs_epoch CHECK (execution_epoch >= 0),
            CONSTRAINT ck_processing_runs_lease_shape CHECK (
                (execution_token IS NULL AND lease_expires_at IS NULL AND worker_id IS NULL)
                OR
                (execution_token IS NOT NULL AND lease_expires_at IS NOT NULL AND worker_id IS NOT NULL)
            )
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_processing_runs_idempotency ON processing_runs(tenant_id, idempotency_key) WHERE idempotency_key IS NOT NULL"
    )
    op.execute("CREATE INDEX ix_processing_runs_tenant_kb_created ON processing_runs(tenant_id, kb_id, created_at DESC)")
    op.execute("CREATE INDEX ix_processing_runs_type_status_created ON processing_runs(run_type, status, created_at)")
    op.execute("CREATE INDEX ix_processing_runs_scope_created ON processing_runs(scope_type, scope_id, created_at DESC)")
    op.execute("CREATE INDEX ix_processing_runs_parent ON processing_runs(parent_run_id)")
    op.execute("CREATE INDEX ix_processing_runs_retry ON processing_runs(retry_of_run_id)")
    op.execute("CREATE INDEX ix_processing_runs_status_heartbeat ON processing_runs(status, heartbeat_at)")
    op.execute("CREATE INDEX ix_processing_runs_status_lease ON processing_runs(status, lease_expires_at)")
    op.execute("COMMENT ON TABLE processing_runs IS '一次完整处理任务的身份、目标、配置、状态和结果；业务权威状态所在（ADR-0018）'")
    op.execute("COMMENT ON COLUMN processing_runs.id IS '内部运行 ID'")
    op.execute("COMMENT ON COLUMN processing_runs.public_id IS 'API、日志和排障使用的稳定公开 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN processing_runs.tenant_id IS '租户隔离过滤'")
    op.execute("COMMENT ON COLUMN processing_runs.kb_id IS '运行所属 KB'")
    op.execute("COMMENT ON COLUMN processing_runs.run_type IS '应用注册的流程类型：source_sync / document_process / rag_index / wiki_generate'")
    op.execute("COMMENT ON COLUMN processing_runs.scope_type IS '处理目标类型：source / revision / knowledge_base / wiki_page'")
    op.execute("COMMENT ON COLUMN processing_runs.scope_id IS '由 scope_type 解释的处理目标逻辑 ID'")
    op.execute("COMMENT ON COLUMN processing_runs.parent_run_id IS '上级编排运行；rag_index / wiki_generate 通常指向产生候选共享 chunk set 的 document_process Run'")
    op.execute("COMMENT ON COLUMN processing_runs.retry_of_run_id IS '终态后发起业务重跑时指向上一 Run；RQ 自动重试不使用'")
    op.execute("COMMENT ON COLUMN processing_runs.attempt_no IS '同一业务重跑链中的 Run 序号；RQ 自动重试不递增'")
    op.execute("COMMENT ON COLUMN processing_runs.trigger_type IS 'manual / on_ingest / schedule / retry'")
    op.execute("COMMENT ON COLUMN processing_runs.status IS 'pending / running / succeeded / failed / cancelled'")
    op.execute("COMMENT ON COLUMN processing_runs.idempotency_key IS '防止 API 重试或重复消息为同一请求创建多次运行'")
    op.execute("COMMENT ON COLUMN processing_runs.effective_config_version IS '本次实际使用的 Source/KB/RAG/Wiki 配置版本，由 run_type 解释'")
    op.execute("COMMENT ON COLUMN processing_runs.options_snapshot IS '共享分块策略、Wiki Map 批次预算、输出语言、Prompt profile 等实际生效的非敏感运行选项快照'")
    op.execute("COMMENT ON COLUMN processing_runs.requested_by_user_id IS '手动触发者；系统任务为空'")
    op.execute("COMMENT ON COLUMN processing_runs.error_code IS 'Run 进入失败终态时的稳定机器错误码；自动重试中的错误归 Span'")
    op.execute("COMMENT ON COLUMN processing_runs.error_message IS 'Run 进入失败终态时的简短错误摘要，不保存完整日志或堆栈'")
    op.execute("COMMENT ON COLUMN processing_runs.execution_token IS '当前执行权的 fencing token；领取 Run 时写入，提交终态/续租必须匹配（ADR-0018）'")
    op.execute("COMMENT ON COLUMN processing_runs.execution_epoch IS '单调递增的执行代号；每次原子领取 Run 时递增，用于拒绝过期 Worker 提交（ADR-0018）'")
    op.execute("COMMENT ON COLUMN processing_runs.lease_expires_at IS '当前执行租约到期时间；未领取时为空（ADR-0018）'")
    op.execute("COMMENT ON COLUMN processing_runs.worker_id IS '持有当前租约的 Worker 标识（ADR-0018）'")
    op.execute("COMMENT ON COLUMN processing_runs.started_at IS '本 Run 第一次被 Worker 实际执行的时间，自动重试不覆盖'")
    op.execute("COMMENT ON COLUMN processing_runs.heartbeat_at IS '运行中最近心跳，用于发现卡死或崩溃任务'")
    op.execute("COMMENT ON COLUMN processing_runs.finished_at IS '成功、失败或取消的结束时间'")
    op.execute("COMMENT ON COLUMN processing_runs.created_at IS '运行创建并进入等待队列的时间'")
    op.execute("COMMENT ON COLUMN processing_runs.updated_at IS '状态、心跳或错误摘要的最近更新时间'")

    # ----- 6.2 processing_spans（阶段树） -----
    op.execute(
        """
        CREATE TABLE processing_spans (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id           UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id           BIGINT NOT NULL,
            kb_id               BIGINT NOT NULL,
            run_id              BIGINT NOT NULL,
            parent_span_id      BIGINT,
            span_name           VARCHAR(50) NOT NULL,
            status              VARCHAR(20) NOT NULL DEFAULT 'pending',
            model_key           VARCHAR(200),
            input_tokens        BIGINT,
            output_tokens       BIGINT,
            metrics             JSONB NOT NULL DEFAULT '{}'::jsonb,
            error_code          VARCHAR(50),
            error_message       VARCHAR(1000),
            started_at          TIMESTAMPTZ,
            finished_at         TIMESTAMPTZ,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_processing_spans_public_id UNIQUE (public_id),
            CONSTRAINT ck_processing_spans_status CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'skipped', 'cancelled')),
            CONSTRAINT ck_processing_spans_input_tokens CHECK (input_tokens IS NULL OR input_tokens >= 0),
            CONSTRAINT ck_processing_spans_output_tokens CHECK (output_tokens IS NULL OR output_tokens >= 0)
        )
        """
    )
    op.execute("CREATE INDEX ix_processing_spans_tenant_kb ON processing_spans(tenant_id, kb_id)")
    op.execute("CREATE INDEX ix_processing_spans_run_created ON processing_spans(run_id, created_at, id)")
    op.execute("CREATE INDEX ix_processing_spans_parent ON processing_spans(parent_span_id)")
    op.execute("CREATE INDEX ix_processing_spans_status_started ON processing_spans(status, started_at)")
    op.execute("CREATE INDEX ix_processing_spans_model_started ON processing_spans(model_key, started_at)")
    op.execute("COMMENT ON TABLE processing_spans IS '一条 processing_runs 总任务拆成的可观测阶段树，保存阶段状态、耗时、模型 token、结构化指标和简短错误诊断'")
    op.execute("COMMENT ON COLUMN processing_spans.id IS '内部阶段 ID'")
    op.execute("COMMENT ON COLUMN processing_spans.public_id IS 'API 和日志追踪使用的稳定阶段 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN processing_spans.tenant_id IS '租户隔离过滤'")
    op.execute("COMMENT ON COLUMN processing_spans.kb_id IS '阶段所属 KB'")
    op.execute("COMMENT ON COLUMN processing_spans.run_id IS '所属 processing_runs 逻辑引用'")
    op.execute("COMMENT ON COLUMN processing_spans.parent_span_id IS '上级阶段逻辑引用，用于表达嵌套阶段树'")
    op.execute("COMMENT ON COLUMN processing_spans.span_name IS '应用注册的阶段名称，如 parse / segment / extract_entities / embed'")
    op.execute("COMMENT ON COLUMN processing_spans.status IS 'pending / running / succeeded / failed / skipped / cancelled'")
    op.execute("COMMENT ON COLUMN processing_spans.model_key IS '该阶段实际使用的模型；非模型阶段为空'")
    op.execute("COMMENT ON COLUMN processing_spans.input_tokens IS '模型阶段输入 token 数'")
    op.execute("COMMENT ON COLUMN processing_spans.output_tokens IS '模型阶段输出 token 数'")
    op.execute("COMMENT ON COLUMN processing_spans.metrics IS '输入/输出项数、缓存命中、重试次数等阶段专属数值指标'")
    op.execute("COMMENT ON COLUMN processing_spans.error_code IS '稳定机器错误码'")
    op.execute("COMMENT ON COLUMN processing_spans.error_message IS '简短错误摘要，不保存完整堆栈'")
    op.execute("COMMENT ON COLUMN processing_spans.started_at IS '阶段实际开始时间；尚未开始便跳过或取消时为空'")
    op.execute("COMMENT ON COLUMN processing_spans.finished_at IS '阶段结束时间'")
    op.execute("COMMENT ON COLUMN processing_spans.created_at IS '记录创建时间'")
    op.execute("COMMENT ON COLUMN processing_spans.updated_at IS '状态、指标或错误摘要更新时间'")

    # ----- 6.3 task_outbox（持久化待投递通知，ADR-0018） -----
    op.execute(
        """
        CREATE TABLE task_outbox (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id              BIGINT NOT NULL,
            task_name           VARCHAR(100) NOT NULL,
            queue_name          VARCHAR(50) NOT NULL,
            available_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            publish_attempts    INTEGER NOT NULL DEFAULT 0,
            lock_token          UUID,
            locked_until        TIMESTAMPTZ,
            published_at        TIMESTAMPTZ,
            last_error          TEXT,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_task_outbox_publish_attempts CHECK (publish_attempts >= 0),
            CONSTRAINT ck_task_outbox_lock_shape CHECK (
                (lock_token IS NULL AND locked_until IS NULL)
                OR
                (lock_token IS NOT NULL AND locked_until IS NOT NULL)
            )
        )
        """
    )
    op.execute("CREATE INDEX ix_task_outbox_ready ON task_outbox(available_at, id) WHERE published_at IS NULL")
    op.execute("CREATE INDEX ix_task_outbox_run ON task_outbox(run_id, id DESC)")
    op.execute("CREATE INDEX ix_task_outbox_lock ON task_outbox(locked_until) WHERE published_at IS NULL")
    op.execute("COMMENT ON TABLE task_outbox IS '与 processing_runs 同事务写入的持久化待投递通知；独立 Publisher 领取后发布到 Taskiq/Redis Streams（ADR-0018）'")
    op.execute("COMMENT ON COLUMN task_outbox.id IS '内部 Outbox 记录 ID'")
    op.execute("COMMENT ON COLUMN task_outbox.run_id IS '关联的 processing_runs 逻辑引用'")
    op.execute("COMMENT ON COLUMN task_outbox.task_name IS '投递的任务名（Handler 路由）'")
    op.execute("COMMENT ON COLUMN task_outbox.queue_name IS '目标队列：critical / default / multimodal / low'")
    op.execute("COMMENT ON COLUMN task_outbox.available_at IS '最早可投递时间（延迟重试）'")
    op.execute("COMMENT ON COLUMN task_outbox.publish_attempts IS '已尝试发布次数'")
    op.execute("COMMENT ON COLUMN task_outbox.lock_token IS 'Publisher 领取锁 token'")
    op.execute("COMMENT ON COLUMN task_outbox.locked_until IS 'Publisher 领取锁到期时间'")
    op.execute("COMMENT ON COLUMN task_outbox.published_at IS '发布成功时间；NULL 表示尚未发布'")
    op.execute("COMMENT ON COLUMN task_outbox.last_error IS '最近一次发布失败原因'")
    op.execute("COMMENT ON COLUMN task_outbox.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN task_outbox.updated_at IS '更新时间'")

    # ========== 7. 检索日志 ==========

    # ----- 7.1 search_logs -----
    op.execute(
        """
        CREATE TABLE search_logs (
            id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            public_id               UUID NOT NULL DEFAULT gen_random_uuid(),
            tenant_id               BIGINT NOT NULL,
            kb_id                   BIGINT NOT NULL,
            user_id                 BIGINT,
            search_path             VARCHAR(20) NOT NULL,
            search_mode             VARCHAR(30) NOT NULL,
            query_text_redacted     TEXT,
            query_fingerprint       CHAR(64) NOT NULL,
            top_k                   INTEGER NOT NULL,
            request_options         JSONB NOT NULL DEFAULT '{}'::jsonb,
            status                  VARCHAR(20) NOT NULL,
            latency_ms              INTEGER NOT NULL,
            result_count            INTEGER NOT NULL,
            result_snapshot         JSONB NOT NULL DEFAULT '[]'::jsonb,
            error_code              VARCHAR(50),
            error_message           VARCHAR(1000),
            feedback_value          SMALLINT,
            feedback_comment        VARCHAR(1000),
            feedback_at             TIMESTAMPTZ,
            created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at              TIMESTAMPTZ NOT NULL,
            updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_search_logs_public_id UNIQUE (public_id),
            CONSTRAINT ck_search_logs_status CHECK (status IN ('succeeded', 'failed')),
            CONSTRAINT ck_search_logs_top_k CHECK (top_k > 0),
            CONSTRAINT ck_search_logs_latency CHECK (latency_ms >= 0),
            CONSTRAINT ck_search_logs_result_count CHECK (result_count >= 0),
            CONSTRAINT ck_search_logs_feedback CHECK (feedback_value IS NULL OR feedback_value IN (-1, 1))
        )
        """
    )
    op.execute("CREATE INDEX ix_search_logs_tenant_kb_created ON search_logs(tenant_id, kb_id, created_at DESC)")
    op.execute("CREATE INDEX ix_search_logs_path_mode_created ON search_logs(search_path, search_mode, created_at DESC)")
    op.execute("CREATE INDEX ix_search_logs_tenant_fingerprint ON search_logs(tenant_id, query_fingerprint)")
    op.execute(
        "CREATE INDEX ix_search_logs_user_created ON search_logs(user_id, created_at DESC) WHERE user_id IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX ix_search_logs_feedback ON search_logs(feedback_value, feedback_at) WHERE feedback_value IS NOT NULL"
    )
    op.execute("CREATE INDEX ix_search_logs_expires ON search_logs(expires_at)")
    op.execute("COMMENT ON TABLE search_logs IS '一次 RAG/Wiki/未来融合搜索请求的脱敏查询、执行方式、性能、命中摘要和单用户反馈'")
    op.execute("COMMENT ON COLUMN search_logs.id IS '内部搜索记录 ID'")
    op.execute("COMMENT ON COLUMN search_logs.public_id IS 'API 和排障使用的稳定请求 ID，全局唯一'")
    op.execute("COMMENT ON COLUMN search_logs.tenant_id IS '租户隔离过滤'")
    op.execute("COMMENT ON COLUMN search_logs.kb_id IS '被搜索的 KB'")
    op.execute("COMMENT ON COLUMN search_logs.user_id IS '发起搜索的用户；Agent 或系统任务为空'")
    op.execute("COMMENT ON COLUMN search_logs.search_path IS 'rag / wiki；预留未来 fused'")
    op.execute("COMMENT ON COLUMN search_logs.search_mode IS '应用注册的具体检索方式，如 keyword / vector / hybrid / fulltext'")
    op.execute("COMMENT ON COLUMN search_logs.query_text_redacted IS '脱敏后的查询文本；租户策略禁止保存文本时为空'")
    op.execute("COMMENT ON COLUMN search_logs.query_fingerprint IS '使用租户级密钥对规范化查询计算的 HMAC 指纹，用于安全地统计重复查询'")
    op.execute("COMMENT ON COLUMN search_logs.top_k IS '请求返回的最大结果数'")
    op.execute("COMMENT ON COLUMN search_logs.request_options IS '过滤条件、权重和 rerank 等非敏感请求快照'")
    op.execute("COMMENT ON COLUMN search_logs.status IS 'succeeded / failed'")
    op.execute("COMMENT ON COLUMN search_logs.latency_ms IS '搜索总耗时'")
    op.execute("COMMENT ON COLUMN search_logs.result_count IS '实际返回结果数量'")
    op.execute("COMMENT ON COLUMN search_logs.result_snapshot IS '有序命中摘要，只保存结果类型、公开 ID、排名、分数和召回通道'")
    op.execute("COMMENT ON COLUMN search_logs.error_code IS '搜索失败时的稳定机器错误码'")
    op.execute("COMMENT ON COLUMN search_logs.error_message IS '搜索失败时的简短错误摘要'")
    op.execute("COMMENT ON COLUMN search_logs.feedback_value IS '单用户反馈：1 有帮助，-1 没帮助'")
    op.execute("COMMENT ON COLUMN search_logs.feedback_comment IS '用户可选反馈说明'")
    op.execute("COMMENT ON COLUMN search_logs.feedback_at IS '最近反馈时间'")
    op.execute("COMMENT ON COLUMN search_logs.created_at IS '搜索发生时间'")
    op.execute("COMMENT ON COLUMN search_logs.expires_at IS '按租户或部署保留策略计算的物理清理时间'")
    op.execute("COMMENT ON COLUMN search_logs.updated_at IS '用户反馈等可变字段更新时间'")


def downgrade() -> None:
    """回滚：按依赖反序 DROP 全部表。不 DROP EXTENSION，避免影响其他 DB。"""
    for table in [
        "search_logs",
        "task_outbox",
        "processing_spans",
        "processing_runs",
        "wiki_page_evidence_refs",
        "wiki_page_document_refs",
        "wiki_page_links",
        "wiki_pages",
        "wiki_folders",
        "content_chunks",
        "document_revisions",
        "documents",
        "sources",
        "kb_wiki_configs",
        "kb_rag_configs",
        "knowledge_bases",
        "user_llm_keys",
        "llm_providers",
        "kb_shares",
        "org_members",
        "organizations",
        "users",
        "tenants",
    ]:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
