"""dramatiq migration: 删 task_outbox 表 + 删 processing_runs fencing/heartbeat 字段

Revision ID: 002
Revises: 001
Create Date: 2026-08-05

设计依据：mydocs/specs/2026-08-05_00-00_Dramatiq任务队列迁移.md

本次迁移配合 Dramatiq + Redis 任务队列切换：
1. 删除 task_outbox 表（Outbox 投递层整体移除，改用 Dramatiq 直接入队 + Reaper 兜底）
2. 删除 processing_runs 的 5 个 fencing/heartbeat 字段：
   - execution_token / execution_epoch / lease_expires_at / worker_id（fencing CAS，ADR-0018 已废弃）
   - heartbeat_at（Run 行心跳改用 span 心跳）
3. 删除相关 CHECK 约束（ck_processing_runs_epoch / ck_processing_runs_lease_shape）
   与索引（ix_processing_runs_status_heartbeat / ix_processing_runs_status_lease）
4. 清理 processing_spans 历史重复行（保留每组 run_id+span_name 最新一行），为 attempt_no 唯一键去重
5. 给 processing_spans 加 attempt_no 字段 + 唯一索引（run_id, attempt_no, span_name）

回滚（downgrade）为 best-effort 恢复，字段约束与索引按 001_initial 重建；
task_outbox 数据回滚后为空；已删除的重复 span 行不可恢复。
"""
from collections.abc import Sequence

from alembic import op

revision: str = "002"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级：删 task_outbox 表 + 删 processing_runs fencing/heartbeat 字段。"""

    # ----- 1. 删 processing_runs 上的 fencing/heartbeat 相关索引与约束 -----
    op.execute("DROP INDEX IF EXISTS ix_processing_runs_status_lease")
    op.execute("DROP INDEX IF EXISTS ix_processing_runs_status_heartbeat")
    op.execute(
        "ALTER TABLE processing_runs DROP CONSTRAINT IF EXISTS ck_processing_runs_lease_shape"
    )
    op.execute(
        "ALTER TABLE processing_runs DROP CONSTRAINT IF EXISTS ck_processing_runs_epoch"
    )

    # ----- 2. 删 processing_runs 的 fencing/heartbeat 字段 -----
    op.execute("ALTER TABLE processing_runs DROP COLUMN IF EXISTS heartbeat_at")
    op.execute("ALTER TABLE processing_runs DROP COLUMN IF EXISTS worker_id")
    op.execute("ALTER TABLE processing_runs DROP COLUMN IF EXISTS lease_expires_at")
    op.execute("ALTER TABLE processing_runs DROP COLUMN IF EXISTS execution_epoch")
    op.execute("ALTER TABLE processing_runs DROP COLUMN IF EXISTS execution_token")

    # ----- 3. 删 task_outbox 表（Outbox 投递层整体移除） -----
    op.execute("DROP TABLE IF EXISTS task_outbox CASCADE")

    # ----- 4. 清理历史重复 span 行（加 attempt_no 唯一键前必须去重） -----
    # 旧表无 attempt_no，重试产生的同 (run_id, span_name) 多行会违反新唯一索引。
    # 保留每组 (run_id, span_name) 最新一行（id 最大），删除更早的重复行。
    op.execute(
        """
        DELETE FROM processing_spans ps
        WHERE ps.id NOT IN (
            SELECT MAX(id)
            FROM processing_spans
            GROUP BY run_id, span_name
        )
        """
    )

    # ----- 5. 给 processing_spans 加 attempt_no 字段（span 唯一键） -----
    op.execute(
        "ALTER TABLE processing_spans ADD COLUMN attempt_no INTEGER NOT NULL DEFAULT 1"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_processing_spans_run_attempt_name "
        "ON processing_spans(run_id, attempt_no, span_name)"
    )


def downgrade() -> None:
    """回滚：按 001_initial 重建 task_outbox 表 + fencing/heartbeat 字段。

    注意：回滚只恢复结构，不恢复数据；task_outbox 数据回滚后为空。
    """

    # ----- 1. 重建 task_outbox 表 -----
    op.execute(
        """
        CREATE TABLE task_outbox (
            id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id              BIGINT NOT NULL,
            task_name           VARCHAR(100) NOT NULL,
            queue_name          VARCHAR(50) NOT NULL,
            available_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            publish_attempts    INTEGER NOT NULL DEFAULT 0,
            lock_token          UUID,
            locked_until        TIMESTAMPTZ,
            published_at        TIMESTAMPTZ,
            last_error          TEXT,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT ck_task_outbox_publish_attempts CHECK (publish_attempts >= 0),
            CONSTRAINT ck_task_outbox_lock_shape CHECK (
                (lock_token IS NULL AND locked_until IS NULL)
                OR
                (lock_token IS NOT NULL AND locked_until IS NOT NULL)
            )
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_task_outbox_ready ON task_outbox(available_at, id) WHERE published_at IS NULL"
    )
    op.execute("CREATE INDEX ix_task_outbox_run ON task_outbox(run_id, id DESC)")
    op.execute("CREATE INDEX ix_task_outbox_lock ON task_outbox(locked_until) WHERE published_at IS NULL")

    # ----- 2. 重建 processing_runs 的 fencing/heartbeat 字段 -----
    op.execute("ALTER TABLE processing_runs ADD COLUMN execution_token UUID")
    op.execute(
        "ALTER TABLE processing_runs ADD COLUMN execution_epoch INTEGER NOT NULL DEFAULT 0"
    )
    op.execute("ALTER TABLE processing_runs ADD COLUMN lease_expires_at TIMESTAMPTZ")
    op.execute("ALTER TABLE processing_runs ADD COLUMN worker_id VARCHAR(255)")
    op.execute("ALTER TABLE processing_runs ADD COLUMN heartbeat_at TIMESTAMPTZ")

    # ----- 3. 重建 CHECK 约束与索引 -----
    op.execute(
        "ALTER TABLE processing_runs ADD CONSTRAINT ck_processing_runs_epoch "
        "CHECK (execution_epoch >= 0)"
    )
    op.execute(
        "ALTER TABLE processing_runs ADD CONSTRAINT ck_processing_runs_lease_shape CHECK ("
        " (execution_token IS NULL AND lease_expires_at IS NULL AND worker_id IS NULL)"
        " OR"
        " (execution_token IS NOT NULL AND lease_expires_at IS NOT NULL AND worker_id IS NOT NULL)"
        ")"
    )
    op.execute(
        "CREATE INDEX ix_processing_runs_status_heartbeat ON processing_runs(status, heartbeat_at)"
    )
    op.execute(
        "CREATE INDEX ix_processing_runs_status_lease ON processing_runs(status, lease_expires_at)"
    )

    # ----- 4. 删 processing_spans 的 attempt_no 字段（回滚 span 唯一键） -----
    op.execute("DROP INDEX IF EXISTS uq_processing_spans_run_attempt_name")
    op.execute("ALTER TABLE processing_spans DROP COLUMN IF EXISTS attempt_no")
